### PR TITLE
Make allow-directory-listing and provide-index-page compatible

### PR DESCRIPTION
**Pull request by AyodeAwe**
This PR follows the discussion that happened in [this issue](https://github.com/nginxinc/nginx-s3-gateway/issues/112).

The PR enables automatic static `index.html` rendering alongside the existing directory listing functionality provided by the library.

***Changes***:
- Architecture becomes thus: initial request is made to get an `index.html` page. If this page is found, it is rendered, otherwise a simple directory listing is done.
- Feature only works if `PROVIDE_INDEX_PAGE` variable is set to true.

_Note_: Due to being an NVIDIA employee I am supposed to request files I modify have an NVIDIA copyright - this explains the included copyright headers.

### CODE REVIEW

**Comment by dekobon** [comment]
Thank you @AyodeAwe for your contribution. Unfortunately, I cannot accept contributions that retain their NVIDIA copyright. Honestly, I am disappointed about that, and I don't like this copyright game we are all stuck in, yet I've got to follow our policy. We also could try to set up a company-to-company contributor agreement, but that's a lot of work for a few number of changes.

Perhaps, this PR can inspire another person to draft their own set of changes without a copyright attached. 

Seriously, myself and the NGINX crew are quite grateful for the contributions. By any chance, do you work with @indianwhocodes or @KodyKantor ?

Kindly,
Elijah

By the way are you working with

**Comment by dekobon** [comment]
> Hey @dekobon I received permission to remove the copyright headers, so I have added a commit to that effect.

Wow, thank you! I will work on the next steps for getting this merged.

**Comment by ajschmidt8** [comment]
@dekobon, just checking in. any updates here?

**Comment by dekobon** [comment]
I've started to review this PR and I'm concerned that the automated tests are failing. I've yet to get enough focus time to determine why they are failing, so if @AyodeAwe or @ajschmidt8 can do this, it would be quite helpful in moving this PR forward.

**Comment by AyodeAwe** [comment]
Just rebased this PR on top of the latest remote commit (af0b2e9). Might need a workflow re-run to see if any errors still come up.

**Comment by AyodeAwe** [comment]
cc: @dekobon  ^^

**Comment by dekobon** [comment]
It looks like the tests are now failing after rebasing. I'll be out of town next week, so I will not be able to make progress. If anyone wants to jump in and offer a fix, that would be appreciated.

**Comment by AyodeAwe** [comment]
Fixed and tested locally. Kindly approve workflow run @dekobon

**Comment by AyodeAwe** [comment]
Just checking on this PR @dekobon. Happy to help if any more work can be done to help move this PR forward.

**Comment by dekobon** [comment]
Right now, I'm working on testing. I've got the PR merged with latest master and it is passing all the tests on my test system. It is just a manner of me getting a solid chunk of time to go through it.

My apologies for the delay.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dekobon** [comment]
Hi @AyodeAwe 

I've made some modifications to the code for this PR (squashing and making a docs change). I've pushed it to: https://github.com/dekobon/nginx-s3-gateway/tree/render-static-index

I would really like to keep the conversation history for this PR in a single place. Would you mind pulling this changes and force pushing them over the branch you have associated with for this PR?

Next, I have an ask regarding the commit titled "allow HEAD requests." Can we either:

1. Remove the commit
2. Fix the gateway such that when doing HEAD requests to subdirectories it does not return a 404 for subdirectories that exist.

If I recall correctly, we do not support subdirectories because I wasn't able (or didn't have the time) to get them to return without doing a 404.

Lastly, I have one more question. Did you test these changes with the v2 signatures enabled?

**Comment by ajschmidt8** [comment]
@dekobon, just a heads up. @AyodeAwe is a colleague of mine and he is out this week. so we may not hear from him until next week.

**Comment by AyodeAwe** [comment]
Ok. I’ve pulled in your changes and removed the 'allow HEAD requests" commit.

Regarding testing with v2, it looks like Signature Version 2 is being turned off (deprecated) by AWS so all requests are naturally now failing. See warning note [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/auth-request-sig-v2.html).

**Comment by AyodeAwe** [comment]
Note @dekobon the `allow HEAD requests` commit (which you asked to remove) fixes the currently failing test case; but this failure should be irrelevant seeing that signature `v2` requests are turned off by AWS. All `v4` tests pass.

The failing test is [this line](https://github.com/nginxinc/nginx-s3-gateway/blob/master/test.sh#L390) (fails when HEAD requests are made to the root `/` directory). It passes when we update the conditional in [this line](https://github.com/nginxinc/nginx-s3-gateway/pull/139/files#diff-7a53ba6d378b8f71917915bcdc8c622f9acc5d2570047164d4207d18ae829a1cL320) to also check for `HEAD` requests and not only `GET`s.

If we must have [this case](https://github.com/nginxinc/nginx-s3-gateway/blob/master/test.sh#L390) (specifically root directory HEAD requests - as other requests in that case assert correctly) pass (even though it is testing with the now deprecated v2 signature), we may need to update the `if` statement as described above.

Thoughts?

**Comment by AyodeAwe** [comment]
Thank you @dekobon, the commit has been re-added.

**Pull request merged**
