### PR TITLE
New minio

### PR DESCRIPTION
**Pull request by zc-devs**
Addresses #60

### CODE REVIEW

**Comment by dekobon** [comment]
The test cases in this PR seem to be failing for me with the following error:
```
+ /home/elijah/go/bin/mc cp -r /home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/ ngt_minio_1/
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/a.txt`. Object name cannot be empty
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/a/c/あ`. Bcket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/a/%!@(MISSING)!*()=$#^&|.txt`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/b/c/'(1).txt`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/a/これは　 is ASCII системы  חן .txt`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/a/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.txt`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/a/plus+plus.txt`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/b/c/d.txt`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/b/c/=`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/b/e.txt`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/b/c/@`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/index.html`. Object name cannot be empty
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/b/クズ箱/ゴxt`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/b/ブツブツ`. Bucket name cannot be shorter than 3 characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/системы/system.txt`. Bucket name contains invalid characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/системы/%!b(MISSING)ad%!f(MISSING)ile%!n(MISSING)ame%!`(MISSING). Bucket name contains invalid characters
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/statichost/index.html`. Bucket `statichost` does not exist.
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/statichost/noindexdir/multipledir/index.html`. Bucket `statichost` does not exist.
mc: <ERROR> Failed to copy `/home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/statichost/noindexdir/noindex.html`. Bucket `statichost` does not exist.
```

Is there another way to get the object onto the MinIO container?

**Comment by zc-devs** [comment]
>Is there another way to get the object onto the MinIO container?

I don't know another way. At least [current approach doesn't work anymore](https://github.com/minio/minio/discussions/15496).

**Comment by zc-devs** [comment]
```
+ /home/elijah/go/bin/mc cp -r /home/elijah/Development/F5/nginx-s3-gateway/test/data/bucket-1/ ngt_minio_1/
```
There is no bucket name in target. Is bucket created? Where is this line from? Cause I don't have it in my logs. How do you run tests?

I run via `sh test.sh` in Windows Bash and get this [test-log-part.txt](https://github.com/nginxinc/nginx-s3-gateway/files/11817398/test-log-part.txt)

**Comment by dekobon** [comment]
What version of `mc` are you using? I'm using:
```
mc version DEVELOPMENT.2023-06-19T19-31-19Z (commit-id=5f39522e69025bea6be0d350b65fdec2de2785c8)
Runtime: go1.20.5 linux/arm64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```

**Comment by zc-devs** [comment]
It was
```
mc version RELEASE.2023-04-12T02-21-51Z (commit-id=1843717c57fb87612469b7610344a7d49d97a497)
Runtime: go1.20.3 windows/amd64
```
But I've just checked on
```
mc version RELEASE.2023-06-19T19-31-19Z (commit-id=5f39522e69025bea6be0d350b65fdec2de2785c8)
Runtime: go1.19.10 windows/amd64
```
and nothing changed - log is the same and all tests pass.

**Comment by dekobon** [comment]
After, I merge with master, the tests are working with the latest changes. Now, I'm scratching my head wondering why the GH Actions are failing.

**Comment by dekobon** [comment]
I've incorporated these changes into a new PR that fixes the CI process: https://github.com/nginxinc/nginx-s3-gateway/pull/146

Could you please review and test?

**Comment by dekobon** [comment]
Fixed in ﻿﻿PR #146

**Pull request closed without merging**
