### PR TITLE
Resolve #53 by fixing multiple encoding problems

### LINKED ISSUE #53: Filenames with brackets () return 404 errors
Hi,

I'm running the the stand-alone container on one of my servers. Problem is, whenever one of the files stored in the S3 container contains brackets, the gateway will return a 404 error.

An example:

Both `image.jpg` and `image(1).jpg` exists in the same bucket in the same folder.

This:
```bash
curl -I "http://127.0.0.1:8011/image.jpg"
```
Returns:
```
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 31 Aug 2022 17:45:21 GMT
Content-Type: image/jpeg
Content-Length: 466483
Connection: keep-alive
Last-Modified: Wed, 31 Aug 2022 17:44:50 GMT
ETag: "b34cf0ebd821a9f892b361e6812571eb"
Accept-Ranges: bytes
```
While this:
```bash
curl -I "http://127.0.0.1:8011/image(1).jpg"
```
Returns:
```
HTTP/1.1 404 Not Found
Server: nginx
Date: Wed, 31 Aug 2022 17:45:27 GMT
Content-Type: text/html
Content-Length: 146
Connection: keep-alive
```

The gateway log shows this:
```
127.0.0.1 - - [31/Aug/2022:17:45:21 +0000] "HEAD /image.jpg HTTP/1.1" 200 0 "-" "curl/7.64.0" "-"
2022/08/31 17:45:21 [info] 61#61: *159 client 127.0.0.1 closed keepalive connection
127.0.0.1 - - [31/Aug/2022:17:45:27 +0000] "HEAD /image(1).jpg HTTP/1.1" 404 0 "-" "curl/7.64.0" "-"
2022/08/31 17:45:27 [info] 61#61: *161 client 127.0.0.1 closed keepalive connection
```

Server details:
```
Debian 8.3.0-6 GNU/Linux 10 (buster)
Linux version 4.19.0-14-cloud-amd64
```

### PR DESCRIPTION
**Pull request by dekobon**
Fixes #53 

This PR addresses problems with:
 * Parenthesis in URLs
 * Some Unicode in URLs (like bidi Hebrew characters)
 * Plus signs in URLs

This PR also adds unit tests in order to catch future encoding issues.

### CODE REVIEW

**Comment by dekobon** [comment]
This is the new PR for this issue (#53). Going forward, let's make changes against this branch and then submit additional PRs.

@sixem @kemoT1990TM @cpeled

**Comment by dekobon** [comment]
I believe this PR now solves the problems with symbols and Unicode characters in object names. However, this PR does not yet have a fix for the index page generating incorrect links to the objects. For example, the index page will generate a URL like the following `http://localhost/a/plus+plus.txt` when it should in fact be `http://localhost/a/plus%2Bplus.txt`.

As long as the URL in the HTML `a href` is not properly encoded, the object may not be consistently returned. In some cases, NGINX makes a best guess as to what it should be, but in many cases it does.

This leaves us with a difficult problem. The index page is generated using XSLT based on the response of an unescaped directory listing returned by S3. There seems to be no support to XSL extensions for the index page. I see a few non-exclusive options:

1. Call this PR good enough, merge it, and then open a new issue for index page links.
2. Fix link encoding in the index page via Javascript.
3. Try to search for another solution.

Thoughts?

**Comment by dekobon** [comment]
@kemoT1990TM What happens when you try to request an object with the plus sign encoded as `%2B`?

**Comment by kemoT1990TM** [comment]
> @kemoT1990TM What happens when you try to request an object with the plus sign encoded as `%2B`?
In this case the error message is:
S3 error response: RequestId=1665046259594210, TraceId=1f8ae499d25b4a36, Resource=/bucket-dev/Product/1.4.0/en/filetype-eppRequisitionType+register-eppHistory.html, HTTP Method=GET, HTTP Status Code=403, X-Forwarded-For: 'xx.xx.xx.xx', ErrorMsg=SignatureDoesNotMatch, ErrorType=ClientAuthorization

**Comment by dekobon** [comment]
> > @kemoT1990TM What happens when you try to request an object with the plus sign encoded as `%2B`?
> > In this case the error message is:
> > S3 error response: RequestId=1665046259594210, TraceId=1f8ae499d25b4a36, Resource=/bucket-dev/Product/1.4.0/en/filetype-eppRequisitionType+register-eppHistory.html, HTTP Method=GET, HTTP Status Code=403, X-Forwarded-For: 'xx.xx.xx.xx', ErrorMsg=SignatureDoesNotMatch, ErrorType=ClientAuthorization

To be clear you are still getting this error when using this (issue/53) branch?

**Review by sixem — COMMENTED** [review]
I would suggest maybe opening another PR to fix the indexing issues with plus symbols. After doing some more testing, it appears to me that using `%2B` instead of `+` has always worked prior to this fix, which makes sense because `A-Z a-z 0-9 - _ . ! ~ * ' ( )` are the only characters not being encoded by default when using `encodeURIComponent()`, and this PR does address the issue with these unescaped characters in particular, so the indexing issue is unrelated to this PR, I think.

I must've gotten thrown off by either browser or web server caching when during testing and switching between `+` and `%2B` ended up always returning 404 errors. Testing it now with only `%2B`, it appears to work for me at least. If anyone else could also confirm this that would be great.

I'm unsure why @kemoT1990TM is still experiencing these issues even with `%2B`, so we may have to look further into that.

**Comment by dekobon** [comment]
> I would suggest maybe opening another PR to fix the indexing issues with plus symbols. After doing some more testing, it appears to me that using `%2B` instead of `+` has always worked prior to this fix, which makes sense because `A-Z a-z 0-9 - _ . ! ~ * ' ( )` are the only characters not being encoded by default when using `encodeURIComponent()`, and this PR does address the issue with these unescaped characters in particular, so the indexing issue is unrelated to this PR, I think.
> 
> I must've gotten thrown off by either browser or web server caching when during testing and switching between `+` and `%2B` ended up always returning 404 errors. Testing it now with only `%2B`, it appears to work for me at least. If anyone else could also confirm this that would be great.
> 
> I'm unsure why @kemoT1990TM is still experiencing these issues even with `%2B`, so we may have to look further into that.

I believe that I've fixed the lingering issues with the latest commit. @kemoT1990TM and @sixem , if you have some time could you verify? So far things seem to be working as I connect directly to AWS and when I test against MinIO.

**Comment by sixem** [comment]
> > I would suggest maybe opening another PR to fix the indexing issues with plus symbols. After doing some more testing, it appears to me that using `%2B` instead of `+` has always worked prior to this fix, which makes sense because `A-Z a-z 0-9 - _ . ! ~ * ' ( )` are the only characters not being encoded by default when using `encodeURIComponent()`, and this PR does address the issue with these unescaped characters in particular, so the indexing issue is unrelated to this PR, I think.
> > I must've gotten thrown off by either browser or web server caching when during testing and switching between `+` and `%2B` ended up always returning 404 errors. Testing it now with only `%2B`, it appears to work for me at least. If anyone else could also confirm this that would be great.
> > I'm unsure why @kemoT1990TM is still experiencing these issues even with `%2B`, so we may have to look further into that.
> 
> I believe that I've fixed the lingering issues with the latest commit. @kemoT1990TM and @sixem , if you have some time could you verify? So far things seem to be working as I connect directly to AWS and when I test against MinIO.

I can confirm that filenames using either `+` or `%2B` work for me now. Tested on both AWS S3 and Backblaze. :+1:

**Comment by dekobon** [comment]
In the last commit, somehow I was able to remember enough XSLT to fix the directory listing issue. I'm quite happy with this PR so far. I really needed the push from @sixem to get started. Thank you and @kemoT1990TM !

I'm going to wait a day before merging to give all of you a chance to test.

**Comment by cpeled** [comment]
Hi.
for some reason, '+' does not work for me with AWS S3. i keep getting 404.
i upload a filename "n ginx.conf" (with space)
this is  the url aws attach the object:  https://<BUCKET_NAME>.eu-central-1.amazonaws.com/n+ginx.conf
when building the s3uri in the gw:  /n%2Bginx.conf

and it just returns 404

any idea?

**Pull request merged**
